#16 fix date not being displayed, type conversion
WitchDevelops/cardboard-fort pull request #25
Opened 2024-06-19 16:16 UTC by WitchDevelops

* made sure that the names of variables match between the database and codebase
* convert Date to a locale string in a separate component

in the database it is stored as `date_of_birth`, type: Date, format: 'YYYY-MM-DD'

2024-06-19 17:23 UTC, nikkehtine requested changes

2024-06-19 17:23 UTC, nikkehtine commented on src/components/PetCard.tsx
> +                <DateOfBirth dateOfBirth={date_of_birth} />
I would revert to how it was before since it's basically one line of code, so that it's easier to read

2024-06-19 18:24 UTC, WitchDevelops commented on src/components/DateOfBirth.tsx
we will have more logic, the default view on the PetCard will be the calculated age, not date of birth: https://github.com/users/WitchDevelops/projects/2/views/1?pane=issue&itemId=67585410

2024-06-20 07:23 UTC, jagodakubicka approved these changes

2024-06-20 07:23 UTC, jagodakubicka commented on src/components/DateOfBirth.tsx
I think we should keep it as separate Component, as we will need to add more logic to it soon

2024-06-22 09:40 UTC, WitchDevelops commented
Overview of changes:

- a separate component for the date was a bad idea. I deleted it.
- instead I created two functions: one that takes the birth date and formats it (to: e.g. `December 12, 2010`), and the other one that calculates age and displays the result as `x years, y months`.
- both functions take input of the `Date` type (directly from the database) and return a type `string`.
- those functions are now in `utils/date`. I suggest we store reusable functions in the `utils` folder and a meaningful subfolder. This helps with modularization of the code and minimizes repeating code.

**How it looks now:**
_on PetCard:_
![image](https://github.com/WitchDevelops/cardboard-fort/assets/112077394/704a4a15-57de-4dc0-845d-929070891c8f)
_on pet page:_
![image](https://github.com/WitchDevelops/cardboard-fort/assets/112077394/3fa8c69c-9396-4cb0-b374-ecb666ae5a03)

**Before changes:**
_on PetCard_ (empty):
![image](https://github.com/WitchDevelops/cardboard-fort/assets/112077394/e082e4d7-2293-43fb-a629-c36c12c0d2b5)
_on pet page:_ (empty, only the date of birth):
![image](https://github.com/WitchDevelops/cardboard-fort/assets/112077394/76a9b076-2f32-4620-8e3b-5e080c46127e)

2024-06-24 13:36 UTC, nikkehtine approved these changes

2024-06-24 13:36 UTC, merged