13 - refactor img into Image component
WitchDevelops/cardboard-fort pull request #31
Opened 2024-06-27 14:36 UTC by jagodakubicka

- Replaced `<img>` with Next.js `<Image />` component for improved performance and optimization.
- Updated next.config.mjs to include multiple trusted domains for images, as recommended by Next.js for enhanced security.
- Implemented responsive sizing using the `sizes` attribute in the `<Image />` component temporarily. Will need to be adjusted during component styling.

2024-06-27 17:48 UTC, WitchDevelops requested changes

2024-06-27 17:48 UTC, WitchDevelops commented on next.config.mjs
In the terminal I see this:
⚠ The "images.domains" configuration is deprecated. Please use "images.remotePatterns" configuration instead.

It's a relatively new thing, but let's keep it fresh :)
StackOverflow re this issue: https://stackoverflow.com/questions/77447587/the-images-domains-configuration-is-deprecated-please-use-images-remotepatte

2024-06-27 21:47 UTC, jagodakubicka commented on next.config.mjs
Fixed! 😊 Thank you for pointing that out!

2024-06-28 06:42 UTC, WitchDevelops requested changes
There are visual issues with how the pet image is being displayed both on mobile and desktop.

on mobile: image it's not displayed at all
on desktop: image is too small, plenty of white space left, it doesn't look good... let's keep the view where the image on left-hand side fills all the available space in the column.

2024-06-28 06:42 UTC, WitchDevelops commented on src/components/BasicInfo.tsx
> +        style={{ gridColumn: '1/2', maxWidth: '200px' }}
I wonder why do we need maxWidth here, it messes up with the view on big screens...

2024-06-28 06:42 UTC, WitchDevelops commented on src/components/BasicInfo.tsx
> +        <div className="relative w-full h-full">
What's the reason behind using relative positioning?

Observation:
pet image is not being displayed on small screens

2024-06-30 10:19 UTC, WitchDevelops approved these changes

2024-06-30 10:20 UTC, merged