#39 update code to match updated DB schema
WitchDevelops/cardboard-fort pull request #40
Opened 2024-06-30 21:39 UTC by WitchDevelops

- [x] created a DB schema with new tables
- [x] tested the schema and calls to  `pets_more_info`, `pets_vaccinations`, and `pets_medications`
- [x] fetched those data and displayed in respective tabs
- [x] exported pet data interface to a separate file and used it in pet tabs and child components
- [ ] `pet_tags` will need some more thought (many-to-many relationship, and we'll probably use some library for this)

![drawSQL-image-export-2024-06-30](https://github.com/WitchDevelops/cardboard-fort/assets/112077394/44302fb6-28dc-4eb2-8db4-206fb19b8bd3)

2024-06-30 21:40 UTC, WitchDevelops commented
plz watch the console, there's some error from next/image that idk when it came up or what to do about it - is it also on main? if yes, then what did I mess up?

2024-06-30 21:41 UTC, WitchDevelops commented on src/pages/user/pets/[pet_id].js
> +  const { data: pet, error: petError } = await supabase
I suppose this DB call could be exported to a separate file

2024-06-30 21:42 UTC, WitchDevelops commented on src/utils/types/petData.ts
> +  pets_more_info?: { pet_bio?: string; microchip_nr?: string };
this prolly can also be extracted into a separate interface

2024-06-30 21:43 UTC, WitchDevelops commented on src/components/Vaccinations.tsx
> +  const [vaccinations, setVaccinations] = React.useState<any[]>([]);
any, will fix later
(needs an interface)

2024-06-30 21:44 UTC, WitchDevelops commented on src/components/PetCard.tsx
> +              {sex ? (
changed coz that is a proper biological term

2024-06-30 21:44 UTC, WitchDevelops commented on src/components/BasicInfo.tsx
> +            width={200}
bumped up the image size to fix poor resolution

2024-06-30 21:45 UTC, WitchDevelops commented on src/components/PetTabs.tsx
> +        <TabsContent value="vaccinations">
would be awesome to add <Suspense> or something to display while fetching the data

2024-07-03 15:29 UTC, jagodakubicka requested changes
- AddPetForm not working, as console throws error: `Could not find the 'name' column of 'pets_data' in the schema cache`
 - pet's name not displayed in PetGrid - PetCard
![image](https://github.com/WitchDevelops/cardboard-fort/assets/93054999/e275c9c1-a1a0-4db1-ac4e-828b6a80b2da)
 - Cannot enter Pet's Data as id is undefined `http://localhost:3000/user/pets/undefined`

2024-07-03 20:01 UTC, jagodakubicka requested changes
- refactor data fetching into try/catch
- clean console.log(pet)

2024-07-05 09:59 UTC, jagodakubicka approved these changes

2024-07-05 09:59 UTC, merged